turtlesite/jizhang/urls.py
from django.conf.urls import patterns, url
from models import *
from views import *

urlpatterns = patterns('',

    url(r'moneyflow/create/$', create_moneyflow, name='create'),
    url(r'moneyflow/list/$', list_moneyflow , name='list'),
    url(r'^$', index , name='index'),
    url(r'moneyflow/edit/(?P<id>[^/]+)/$', edit_moneyflow, name='edit'),
    url(r'moneyflow/view/(?P<id>[^/]+)/$', view_moneyflow, name='view'),
    url(r'moneyflow/test/$', test_moneyflow , name='test'),
    
)

turtlesite/polls/urls.py
from django.conf.urls import patterns, url
from django.views.generic import DetailView, ListView
from polls.models import Poll

urlpatterns = patterns('',
    url(r'^$',
        ListView.as_view(
            queryset=Poll.objects.order_by('-pub_date')[:5],
            context_object_name='latest_poll_list',
            template_name='polls/index.html'),
        name='index'),
    url(r'^(?P<pk>\d+)/$',
        DetailView.as_view(
            model=Poll,
            template_name='polls/detail.html'),
        name='detail'),
    url(r'^(?P<pk>\d+)/results/$',
        DetailView.as_view(
            model=Poll,
            template_name='polls/results.html'),
        name='results'),
    url(r'^(?P<poll_id>\d+)/vote/$', 'polls.views.vote', name='vote'),
)

turtlesite/ppb/urls.py
from django.conf.urls import patterns, url

from ppb import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
)

turtlesite/turtlesite/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'turtlesite.views.home', name='home'),
    # url(r'^turtlesite/', include('turtlesite.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    url(r'^polls/', include('polls.urls', namespace="polls")),
    url(r'^ppb/',   include('ppb.urls', namespace="ppb")),
    url(r'^jizhang/',   include('jizhang.urls', namespace="jizhang")),
)

turtlesite/jizhang/models.py
from django.db import models
from django.utils import timezone

class MoneyFlow(models.Model):
    title = models.CharField(max_length=200)
    details = models.CharField(max_length=3000, null=True)
    amount = models.FloatField()
    owner = models.CharField(max_length=20)
    is_income = models.BooleanField(default=False)
    occured_date = models.DateTimeField('date occured', auto_now_add=True)
    change_date = models.DateTimeField('date changed', auto_now_add=True)

    def __unicode__(self):
        return self.title + " " + self.details

turtlesite/polls/models.py
import datetime
from django.utils import timezone
from django.db import models

class Poll(models.Model):
    question = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __unicode__(self):
        return self.question

    def was_published_recently(self):
        now = timezone.now()
        return now-datetime.timedelta(days=1) <= self.pub_date < now

    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'

class Choice(models.Model):
    poll = models.ForeignKey(Poll)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __unicode__(self):
        return self.choice_text

turtlesite/jizhang/forms.py
from django import forms
from models import *



class MoneyFlowForm(forms.ModelForm):
	
    class Meta:
        model = MoneyFlow
        #fields = ()	
        exclude = [] # uncomment this line and specify any field to exclude it from the form

    def __init__(self, *args, **kwargs):
        super(MoneyFlowForm, self).__init__(*args, **kwargs)

turtlesite/jizhang/views.py
# -*- coding: utf-8 -*-
# Create your views here.

from django import forms
from django.template import RequestContext
from django.http import HttpResponse, HttpResponseRedirect
from django.template.loader import get_template
from django.core.paginator import Paginator
from django.core.urlresolvers import reverse

# app specific files

from models import *
from forms import *

def index(request):
  
    list_items = MoneyFlow.objects.all().order_by('occured_date')
    paginator = Paginator(list_items ,10)


    try:
        page = int(request.GET.get('page', '1'))
    except ValueError:
        page = 1

    try:
        list_items = paginator.page(page)
    except :
        list_items = paginator.page(paginator.num_pages)

    (income_sum, outcome_sum) = per_month_amount_sum()

    t = get_template('jizhang/index.html')
    c = RequestContext(request,locals())
    return HttpResponse(t.render(c))

def per_month_amount_sum():

    list_items = MoneyFlow.objects.all()
    outcome_sum = 0
    income_sum = 0
    for item in list_items:
        if item.is_income:
            income_sum += item.amount
        else:
            outcome_sum += item.amount


    return (income_sum, outcome_sum)


def create_moneyflow(request):
    form = MoneyFlowForm(request.POST or None)
    if form.is_valid():
        form.save()
        form = MoneyFlowForm()

    t = get_template('jizhang/create_moneyflow.html')
    c = RequestContext(request,locals())
    return HttpResponse(t.render(c))



def list_moneyflow(request):
  
    list_items = MoneyFlow.objects.all()
    paginator = Paginator(list_items ,10)


    try:
        page = int(request.GET.get('page', '1'))
    except ValueError:
        page = 1

    try:
        list_items = paginator.page(page)
    except :
        list_items = paginator.page(paginator.num_pages)

    t = get_template('jizhang/list_moneyflow.html')
    c = RequestContext(request,locals())
    return HttpResponse(t.render(c))



def view_moneyflow(request, id):
    moneyflow_instance = MoneyFlow.objects.get(id = id)

    t=get_template('jizhang/view_moneyflow.html')
    c=RequestContext(request,locals())
    return HttpResponse(t.render(c))

def edit_moneyflow(request, id):

    moneyflow_instance = MoneyFlow.objects.get(id=id)

    form = MoneyFlowForm(request.POST or None, instance = moneyflow_instance)

    if form.is_valid():
        form.save()

    t=get_template('jizhang/edit_moneyflow.html')
    c=RequestContext(request,locals())
    return HttpResponse(t.render(c))


def test_moneyflow(request):
  
    t = get_template('jizhang/test.html')
    c = RequestContext(request,locals())
    return HttpResponse(t.render(c))

turtlesite/jizhang/templates/jizhang/create_moneyflow.html
{% extends "base.html" %}

{% block title %} MoneyFlow - Create {% endblock %}

{% block heading %}<h1>  MoneyFlow - Create </h1>  {% endblock %}
{% block content %} 
<table>
<form action="" method="POST"> {% csrf_token %}
  {{form}}
  <tr>
    <td colspan="2" align="right"><input type="submit" value="Create"/></td>
  </tr>
</form>
</table>
{% endblock %}

turtlesite/jizhang/templates/jizhang/edit_moneyflow.html
{% extends "base.html" %}

{% block title %} MoneyFlow - Edit {% endblock %}

{% block heading %} <h1> MoneyFlow</h1><h2> Edit </h2> {% endblock %}
{% block content %} 
<table>
<form action="" method="POST"> {% csrf_token %}
  {{form}}
  <tr>
    <td colspan="2" align="right"><input type="submit" value="Save"/></td>
  </tr>
</form>
</table>
{% endblock %}

turtlesite/jizhang/templates/jizhang/index.html
<!DOCTYPE html>

{% load staticfiles %}


<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
	<title>jizhang 记账</title>
	<link rel="stylesheet" href="{% static 'jizhang/css/bootstrap.min.css' %}">
</head>
<body>

<div class="container">
    
<div class="row">
  <div class="span9">
    <h1>总览</h1>
    <div class="row">
      <div class="span6">
        <h2>明细</h2>
        
        <table>
        <thead>
            <tr>
                <th>Date</th>
                <th>Title</th>
                <th>Amount</th>
                <th colspan="3">Actions</th>
            </tr>
        </thead>
        {% for item in list_items.object_list %}
        <tr>
            <td>  {{item.occured_date}}</td> 
            <td>  {{item}}</td> 
            <td>  {{item.amount}}</td> 
            <td><a href="{% url 'jizhang:view' item.id %}">Show</a> </td> 
            <td><a href="{% url 'jizhang:edit' item.id %}">Edit</a>
        </tr>
        {% endfor %}
        <tr><td colspan="3"> <a href="{% url 'jizhang:create' %}">Add New</a></td></tr>
        </table>

        <div align="center">
        {% if list_items.has_previous %}
            <a href="?page={{ list_items.previous_page_number }}">Previous</a>
        {% endif %}
        
        <span class="current">
            Page {{ list_items.number }} of {{ list_items.paginator.num_pages }}.
        </span>
        
        {% if list_items.has_next %}
                <a href="?page={{ list_items.next_page_number }}">Next</a>
        {% endif %}
        
        </div>
      </div>

      <div class="span3">
        <h2>汇总</h2>
        <table>
            <thead>
                <tr>
                    <th>月份</th>
                    <th>总消费</th>
                    <th>总收入</th>
                    <th>差额</th>
                </tr>
            </thead>
            <tr>
                <td>2013-04</td>
                <td>{{outcome_sum}}</td>
                <td>{{income_sum}}</td>
                
            </tr>
        </table>
      </div>

      <div class="span3">
        <h2>分类</h2>
        <table>
            <thead>
                <tr>
                    <th>类别</th>
                    <th>总额</th>
                    <th>比例</th>
                </tr>
            </thead>
        </table>
      </div>

      <div class="span3">
        <h2>分人</h2>
        <table>
            <thead>
                <tr>
                    <th>owner</th>
                    <th>总额</th>
                    <th>比例</th>
                </tr>
            </thead>
        </table>
      </div>

    </div>
  </div>
</div>




</div>

<div id="explanation" align="center">
<a href="{% url 'jizhang:index' %}">jizhang 记账</a>
</div>



</body>
</html>

turtlesite/jizhang/templates/jizhang/list_moneyflow.html
{% extends "base.html" %}

{% block title %} <h1> MoneyFlow </h1><h2> List </h2> {% endblock %}

{% block heading %} 
<h1> MoneyFlow</h1>
<h2> List Records</h2>
{% endblock %}
{% block content %} 

<table>
<thead>
<tr><th>Record</th><th colspan="3">Actions</th></tr>
{% for item in list_items.object_list %}
  <tr><td>  {{item}}</td> <td><a href="{% url 'jizhang:view' item.id %}">Show</a> </td> <td><a href="{% url 'jizhang:edit' item.id %}">Edit</a></tr>
{% endfor %}
<tr><td colspan="3"> <a href="{% url 'jizhang:create' %}">Add New</a></td></tr>
</table>

<div align="center">
{% if list_items.has_previous %}
    <a href="?page={{ list_items.previous_page_number }}">Previous</a>
{% endif %}

<span class="current">
    Page {{ list_items.number }} of {{ list_items.paginator.num_pages }}.
</span>

{% if list_items.has_next %}
        <a href="?page={{ list_items.next_page_number }}">Next</a>
{% endif %}

</div>
{% endblock %}

turtlesite/jizhang/templates/jizhang/results.html
<h1>{{ poll.question }}</h1>

<ul>
{% for choice in poll.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' poll.id %}">Vote again?</a>


turtlesite/jizhang/templates/jizhang/test.html
{% load staticfiles %}

<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
	<title>productlist</title>
	<link rel="stylesheet" href="{% static 'jizhang/css/bootstrap.min.css' %}">
</head>
<body>
<div class="container">	
	<div class="page-header">
    <h2>产品清单</h2>
  </div>

	<div class="row" style="padding-top:10">
    	<div class="span3 media-grid">
    		<a href="#">
		    <img class="thumbnail" src="http://img1.douban.com/mpic/s6983462.jpg" alt="">
		    </a>
    	</div>
    	<div class="span-two-thirds">
   			<h4>黄瓜的黄 西瓜的西</h4>
			本书是著名华裔笑星黄西的第一本书，涉及他在中国的成长、在美国的经历以及从生化博士到脱口秀演员的道路。
			　　黄西从小有礼貌但不是很听老师的话。中学老师说他考不上大学，后来因为不想让一位慈母般的老师失望而努力学习，考上吉林大学，并以第一名的成绩考入中科院研究生院。为了考GRE去美国留学，他把牛津词典背了8遍；在莱斯大学求学期间他经常在实验室里努力工作到凌晨一两点，有连续两年的时间只休过一个周末，最后拿到生化博士学位；后来工作期间，他白天去公司的做医药实验，晚上去俱乐部说相声；为了能到俱乐部演出，他在大雪天里站在俱乐部外面询问路过的人是否愿意进去听他讲相声……
    	</div>
		<div class="span2" style="align:right">
			<p><button class="btn primary">查看</button> </p>
			<p><button class="btn success">编辑</button> </p>
			<p><button class="btn danger">删除</button></p>
		</div>
    </div>

	<div class="row" style='background-color: #F0F0F0; padding-top:10'>
    	<div class="span3 media-grid">
    		<a href="#">
		    <img class="thumbnail" src="http://img1.douban.com/mpic/s7015751.jpg" alt="">
		    </a>
    	</div>
    	<div class="span-two-thirds">
   			<h4>考拉小巫的英语学习日记</h4>
			这本书的出版是献给考拉小巫粉丝以及所有英语学习爱好者的一份礼物。在这本书里，考拉小巫分享了她人生中各个阶段学习英语的所有方法途径及心得体会，和她为了从根本上提高英语听、说、读、写、译能力所做的一切失败和成功的尝试及努力，以及她考过的所有英语考试的备考方案、计划安排、所用书籍及资料，书后附录中还有作者总结的英语学习资料及资源推荐。
    	</div>
		<div class="span2">
			<p><button class="btn primary">查看</button> </p>
			<p><button class="btn success">编辑</button> </p>
			<p><button class="btn danger">删除</button></p>
		</div>
    </div>

	<div class="row" style="padding-top:10">
    	<div class="span3 media-grid">
    		<a href="#">
		    <img class="thumbnail" src="http://img3.douban.com/mpic/s7020493.jpg" alt="">
		    </a>
    	</div>
    	<div class="span-two-thirds">
   			<h4>突然就走到了西藏</h4>
			　陈坤动情自述从出身贫寒的“北漂”青年一夜成名到找回自我，继而重新上路的成长历程。关于亲情与友情、家庭与事业、名利与信仰的心灵全纪录。
			　　本书记录了陈坤带领十名大学生志愿者行走西藏过程中，对生命的点滴感悟。穿插了他成名前后生活中的小故事。笔端情感真挚，读来亲切自然。
			　　“只要你行走，就能与你生命中的真相相遇。”——陈坤
			　　这不只是一本明星写的带有自传色彩的书，更是一个在世间行走的人老老实实的心灵告白，你可以读到他的挣扎，他的茫然和转化。这本书也不仅关乎心灵，更关乎现世人生，关乎如何看待这个世界，看待这个无常世界里的命运变幻。
    	</div>
		<div class="span2">
			<p><button class="btn primary">查看</button> </p>
			<p><button class="btn success">编辑</button> </p>
			<p><button class="btn danger">删除</button></p>
		</div>
    </div>
</div>
</body>
</html>

turtlesite/jizhang/templates/jizhang/view_moneyflow.html
{% extends "base.html" %}

{% block title %} MoneyFlow - View {% endblock %}

{% block heading %} <h1> MoneyFlow</h1><h2>View</h2>  {% endblock %}
{% block content %} 
<table>
{{ moneyflow_instance }}
</table>
{% endblock %}